steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  
  # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]

  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=gke.yaml                    #name of deploymen file
    - --image=gcr.io/$PROJECT_ID/gcpdevops   #name of docker image
    - --location=us-central1-c               #location of cluster
    - --cluster=devops-cluster           #name of cluster
    - --namespace=devops-ns           #name of namespace in cluster
